services:
    ols4-solr:
      image: solr:9.8.1
      user: "${UID:?}:${GID:?}"
      environment:
        - SOLR_HOME=/mnt/solr
        - JAVA_OPTS=--add-modules jdk.incubator.vector
      ports:
        - 8983:8983
      volumes:
        - ./out/solr/server/solr:/mnt/solr
      command: ["-f"]
    ols4-neo4j:
      image: neo4j:2025.03.0-community
      user: "${UID:?}:${GID:?}"
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - ./out/neo4j/data:/var/lib/neo4j/data
      environment:
        - NEO4J_AUTH=none
        - JAVA_OPTS=--add-modules jdk.incubator.vector
    ols4-backend:
      user: "${UID:?}:${GID:?}"
      build:
        context: .
        dockerfile: ./backend/Dockerfile
      ports:
        - 8080:8080
      environment:
        - OLS_SOLR_HOST=http://ols4-solr:8983
        - OLS_NEO4J_HOST=bolt://ols4-neo4j:7687
      depends_on:
        - ols4-solr
        - ols4-neo4j
      links:
        - ols4-solr
        - ols4-neo4j
    ols4-frontend:
      user: "${UID:?}:${GID:?}"
      build:
        context: ./frontend
      env_file: ./frontend/.env
      ports:
        - 8081:8080
      depends_on:
        - ols4-backend
      links:
        - ols4-backend
    run-api-tests:
      profiles: ["run-api-tests"]
      build: ./apitester4
      user: "${UID:?}:${GID:?}"
      volumes:
        - ./testcases_output_api:/mnt/out:rw
        - ./testcases_expected_output_api:/mnt/compare:rw
      command: ["bash", "-c", "java -jar /opt/apitester/target/apitester-1.0-SNAPSHOT-jar-with-dependencies.jar --url http://ols4-backend:8080 --outDir /mnt/out --compareDir /mnt/compare --deep > /mnt/out/apitester4.log"]
      depends_on:
        - ols4-backend
      links:
        - ols4-backend