version: '3'
services:
    ols4-dataload:
      build: ./dataload
      volumes:
        - ols4-solr-data:/opt/solr/server/solr/ols4:rw
        - ols4-neo4j-data:/opt/neo4j/data:rw
        - ./${OLS4_CONFIG:?OLS4 dataload requires a config file}:/mnt/config.json:ro
          #- ./docker_out:/tmp/out:rw
    ols4-solr:
      image: solr:9
      environment:
        - SOLR_HOME=/mnt/ols4-solr-data
      ports:
        - 8983:8983
      volumes:
        - ols4-solr-data:/mnt/ols4-solr-data
      command: ["-f"]
      depends_on:
        ols4-dataload:
          condition: service_completed_successfully
    ols4-neo4j:
      image: neo4j:4.4.9-community
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - ols4-neo4j-data:/var/lib/neo4j/data
      environment:
        - NEO4J_AUTH=none
      depends_on:
        ols4-dataload:
          condition: service_completed_successfully
    ols4-server:
      build: ./server
      ports:
        - 8080:8080
      environment:
        - OLS_SOLR_HOST=http://ols4-solr:8983
        - OLS_NEO4J_HOST=bolt://ols4-neo4j:7687
      depends_on:
        - ols4-solr
        - ols4-neo4j    
      links:
        - ols4-solr
        - ols4-neo4j 
    run-api-tests:
      profiles: ["run-api-tests"]
      build:
        context: .
        dockerfile: apitest.Dockerfile
      depends_on:
        - ols4-server
      links:
        - ols4-server
volumes:
    ols4-solr-data:
    ols4-neo4j-data:



