services:
    ols4-postgres:
      image: pgvector/pgvector:0.8.0-pg17
      user: "${HOST_UID:?}:${HOST_GID:?}"
      shm_size: '2g'
      ports:
        - 5432:5432
      volumes:
        - ./out/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PGDATA=/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -h /tmp -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 30
        start_period: 10s
    ols4-backend:
      user: "${HOST_UID:?}:${HOST_GID:?}"
      image: ${OLS4_BACKEND_IMAGE:-ghcr.io/ebispot/ols4-backend:dev}
      build:
        context: .
        dockerfile: ./backend/Dockerfile
      ports:
        - 8080:8080
      environment:
        - OLS_POSTGRES_HOST=ols4-postgres
        - OLS_POSTGRES_PORT=5432
        - OLS_POSTGRES_DB=ols4
        - OLS_POSTGRES_USER=postgres
        - OLS_TEXT_TAGGER_DB=/mnt/text_tagger_db.bin

      volumes:
        - ./out/text_tagger_db.bin:/mnt/text_tagger_db.bin:ro
      depends_on:
        ols4-postgres:
          condition: service_healthy
      links:
        - ols4-postgres
    ols4-frontend:
      user: "${HOST_UID:?}:${HOST_GID:?}"
      image: ${OLS4_FRONTEND_IMAGE:-ghcr.io/ebispot/ols4-frontend:dev}
      build:
        context: ./frontend
      env_file: ./frontend/.env
      ports:
        - 8081:8080
      depends_on:
        - ols4-backend
      links:
        - ols4-backend
    run-api-tests:
      profiles: ["run-api-tests"]
      image: ${OLS4_APITESTER_IMAGE:-ghcr.io/ebispot/ols4-apitester4:dev}
      build: ./apitester4
      user: "${HOST_UID:?}:${HOST_GID:?}"
      environment:
        - HOME=/tmp
      volumes:
        - ./testcases_output_api:/mnt/out:rw
        - ./testcases_expected_output_api:/mnt/compare:rw
      command: ["bash", "-c", "set -o pipefail; java -jar /opt/apitester/apitester.jar --url http://ols4-backend:8080 --outDir /mnt/out --compareDir /mnt/compare --deep 2>&1 | tee /mnt/out/apitester4.log"]
      depends_on:
        - ols4-backend
      links:
        - ols4-backend