[package]
name = "ols_json2solr"
version = "1.0.0"
edition = "2024"
rust-version = "1.90.0"

[[bin]]
name = "ols_json2solr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
parquet = "54.1"
arrow = { version = "54.1", features = ["ffi"] }
thiserror = "2.0"
indexmap = { version = "2.7", features = ["serde"] }
struson = "0.5"
ols_shared = { path = "../ols-shared-rs" }

[profile.release]
lto = true
codegen-units = 1
strip = true
