[package]
name = "rdf2json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "rdf2json"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
flate2.workspace = true
ureq.workspace = true
oxrdf.workspace = true
oxrdfio.workspace = true
regex.workspace = true
struson.workspace = true
ols_shared.workspace = true
