apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - hh-rke-wp-webadmin-56-worker-3.caas.ebi.ac.uk
      containers:
        - name: web
          image: ghcr.io/ebispot/ols4-backend:{{.Values.imageTag}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 10Gi
              cpu: 0.5
            limits:
              memory: 10Gi
              cpu: 2
          env:
            - name: OLS_SOLR_HOST
              value: http://{{ .Release.Name }}-solr:8983
            - name: OLS_NEO4J_HOST
              value: bolt://{{ .Release.Name }}-neo4j:7687
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /ols4
            - name: JAVA_OPTIONS
              value: -Xmx6G
              
