apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - hh-rke-wp-webadmin-56-worker-3.caas.ebi.ac.uk
      volumes:
        - name: {{ .Release.Name }}-import
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-import-pvc
      containers:
        - name: web
          image: ghcr.io/ebispot/ols4-backend:{{.Values.imageTag}}
          volumeMounts:
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ols4/api/v2/health  # Ensure this matches the context path
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: {{ .Release.Name }}-backend
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: 10Gi
              cpu: 0.5
            limits:
              memory: 10Gi
              cpu: 2
          env:
            - name: OLS_SOLR_HOST
              value: http://{{ .Release.Name }}-solr:8983
            - name: OLS_NEO4J_HOST
              value: bolt://{{ .Release.Name }}-neo4j:7687
            - name: OLS_EMBEDDING_SERVICE_URL
              value: http://wwwdev.ebi.ac.uk/spot/embed
            - name: OLS_EMBEDDING_PCA_MODELS_DIR
              value: /data_import
            - name: HTTP_PROXY
              value: http://hx-wwwcache.ebi.ac.uk:3128
            - name: HTTPS_PROXY
              value: http://hx-wwwcache.ebi.ac.uk:3128
            - name: http_proxy
              value: http://hx-wwwcache.ebi.ac.uk:3128
            - name: https_proxy
              value: http://hx-wwwcache.ebi.ac.uk:3128
            - name: no_proxy
              value: localhost,.cluster.local
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /ols4
            - name: SPRING_AI_MCP_SERVER_BASE_URL
              value: /ols4
            - name: JDK_JAVA_OPTIONS
              value: "-Xmx6G -Dhttp.proxyHost=hx-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128"
              
