apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - hh-rke-wp-webadmin-56-worker-2.caas.ebi.ac.uk
      containers:
        - name: web
          image: ghcr.io/ebispot/ols4-frontend:{{.Values.imageTag}}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.25
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_APIURL
              value: https://www.ebi.ac.uk/ols4/
            - name: PUBLIC_URL
              value: /ols4
            - name: OLS_MINIFY
              value: 'true'
          command: ["/bin/bash", "-c"]
          args: ["/opt/ols4-frontend/entrypoint.dockersh"]


