apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ols4-postgres-pvc
spec:
  storageClassName: local-storage
  volumeName: ols4-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
