apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  ports:
      - port: 8983
        targetPort: 8983
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-solr