apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-configmap
data:
  HTTP_PROXY: http://hx-wwwcache.ebi.ac.uk:3128
  HTTPS_PROXY: http://hx-wwwcache.ebi.ac.uk:3128
  http_proxy: http://hx-wwwcache.ebi.ac.uk:3128
  https_proxy: http://hx-wwwcache.ebi.ac.uk:3128
  no_proxy: localhost,.cluster.local
