apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  name: ols4-pv-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 250Gi
  local:
    path: /var/local-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hh-rke-wp-webadmin-47-worker-1.caas.ebi.ac.uk
          - hh-rke-wp-webadmin-47-worker-2.caas.ebi.ac.uk
          - hh-rke-wp-webadmin-47-worker-3.caas.ebi.ac.uk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

