###
### Read-only NFS mounts to copy data from
###
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations: {}
  finalizers:
    - kubernetes.io/pv-protection
  name: {{ .Release.Name }}-import-pv
spec:
  accessModes: ['ReadOnlyMany']
  storageClassName: standard-nfs-production
  volumeMode: Filesystem
  mountOptions: ['nfsvers=3']
  nfs:
    server: {{ .Values.nfs_host }}
    path: {{ .Values.nfs_path }}
  capacity:
    storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-import-pvc
spec:
  storageClassName: standard-nfs-production
  volumeName: {{.Release.Name}}-import-pv
  accessModes: ['ReadOnlyMany']
  resources:
    requests:
      storage: 1000Gi
