apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: web
          image: ghcr.io/ebispot/ols4-frontend:{{.Values.imageTag}}
          imagePullPolicy: Always
          resources:
              requests:
                cpu: 2
                memory: 4G          
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_APIURL
              value: {{.Values.frontend.apiUrl}}
            - name: PUBLIC_URL
              value: {{.Values.frontend.publicUrl}}

