apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hh-rke-wp-webadmin-47-worker-3.caas.ebi.ac.uk
                - hx-rke-wp-webadmin-40-worker-3.caas.ebi.ac.uk