apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: web
          image: ghcr.io/ebispot/ols4-backend:{{.Values.imageTag}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ols4/api/v2/health
              port: 8080
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: {{ .Release.Name }}-backend
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: 10Gi
              cpu: 0.5
            limits:
              memory: 50Gi
              cpu: 2
          env:
            - name: OLS_SOLR_HOST
              value: http://{{ .Release.Name }}-solr:8983
            - name: OLS_NEO4J_HOST
              value: bolt://{{ .Release.Name }}-neo4j:7687
            - name: OLS_EMBEDDING_SERVICE_URL
              value: http://wwwdev.ebi.ac.uk/spot/embed
            - name: OLS_EMBEDDING_PCA_MODELS_DIR
              value: /data/pca_models
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /ols4
            - name: SPRING_AI_MCP_SERVER_BASE_URL
              value: /ols4
            - name: JDK_JAVA_OPTIONS
              value: "-XX:InitialRAMPercentage=60.0 -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=80.0 -Dhttp.proxyHost=hx-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128"
          volumeMounts:
            - mountPath: "/data"
              name: embeddings
              readOnly: true
      volumes:
        - name: embeddings
          persistentVolumeClaim:
            claimName: {{ include "ols4.fullname" . }}-embeddings
