apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/ols4$ /ols4/ permanent;
spec:
  rules:
    - http:
        paths:
          - path: /ols4/api/mcp
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mcp
                port:
                  number: 8080
          - path: /ols4/api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 8080
          - path: /ols4/swagger-ui
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 8080
          - path: /ols4/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 8080
          - path: /ols4
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 8080