apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - hh-rke-wp-webadmin-47-worker-1.caas.ebi.ac.uk
                      - hx-rke-wp-webadmin-40-worker-1.caas.ebi.ac.uk
      volumes:
          - name: {{ .Release.Name }}-solr-storage
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-solr-pvc
          - name: {{ .Release.Name }}-import
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-import-pvc
      securityContext:
        fsGroup: 8983
      containers:
        - name: solr
          image: ghcr.io/ebispot/ols4-solr:9.8.1
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Release.Name }}-solr-storage
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
          command: ["/bin/bash", "-c"]
          args: ["echo Downloading data && rm -rf /data/solr && mkdir /data/solr && cat /data_import/solr.tgz | tar -xz --skip-old-files -C /data/ && echo Starting solr && solr-foreground -a -XX:CompileCommand=exclude,com.github.benmanes.caffeine.cache.BoundedLocalCache::put"]
          resources:
            requests:
              memory: 15Gi
              cpu: 3
            limits:
              memory: 20Gi
              cpu: 4
          env:
            - name: SOLR_HOME
              value: /data
            - name: SOLR_JAVA_MEM
              value: -Xms2g -Xmx8g
            - name: JAVA_OPTS
              value: --add-modules jdk.incubator.vector
          ports:
            - containerPort: 8983

