/// Defined fields matching the Java DefinedFields enum
#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
pub enum DefinedFields {
    AppearsIn,
    BaseUri,
    DefinedBy,
    Definition,
    DirectAncestor,
    DirectParent,
    ExportsTo,
    HasDirectChildren,
    HasDirectParents,
    HasHierarchicalChildren,
    HasHierarchicalParents,
    HasIndividuals,
    HasLocalDefinition,
    HierarchicalAncestor,
    HierarchicalParent,
    Imported,
    ImportsFrom,
    IsDefiningOntology,
    IsObsolete,
    IsPreferredRoot,
    Label,
    Language,
    MailingList,
    NumDescendants,
    NumHierarchicalDescendants,
    OntologyPurl,
    PreferredRoot,
    RelatedFrom,
    RelatedTo,
    LinksTo,
    Synonym,
}

impl DefinedFields {
    pub fn text(&self) -> &'static str {
        match self {
            DefinedFields::AppearsIn => "appearsIn",
            DefinedFields::BaseUri => "baseUri",
            DefinedFields::DefinedBy => "definedBy",
            DefinedFields::Definition => "definition",
            DefinedFields::DirectAncestor => "directAncestor",
            DefinedFields::DirectParent => "directParent",
            DefinedFields::ExportsTo => "exportsTo",
            DefinedFields::HasDirectChildren => "hasDirectChildren",
            DefinedFields::HasDirectParents => "hasDirectParents",
            DefinedFields::HasHierarchicalChildren => "hasHierarchicalChildren",
            DefinedFields::HasHierarchicalParents => "hasHierarchicalParents",
            DefinedFields::HasIndividuals => "hasIndividuals",
            DefinedFields::HasLocalDefinition => "hasLocalDefinition",
            DefinedFields::HierarchicalAncestor => "hierarchicalAncestor",
            DefinedFields::HierarchicalParent => "hierarchicalParent",
            DefinedFields::Imported => "imported",
            DefinedFields::ImportsFrom => "importsFrom",
            DefinedFields::IsDefiningOntology => "isDefiningOntology",
            DefinedFields::IsObsolete => "isObsolete",
            DefinedFields::IsPreferredRoot => "isPreferredRoot",
            DefinedFields::Label => "label",
            DefinedFields::Language => "language",
            DefinedFields::MailingList => "mailingList",
            DefinedFields::NumDescendants => "numDescendants",
            DefinedFields::NumHierarchicalDescendants => "numHierarchicalDescendants",
            DefinedFields::OntologyPurl => "ontologyPurl",
            DefinedFields::PreferredRoot => "preferredRoot",
            DefinedFields::RelatedFrom => "relatedFrom",
            DefinedFields::RelatedTo => "relatedTo",
            DefinedFields::LinksTo => "linksTo",
            DefinedFields::Synonym => "synonym",
        }
    }
}
