
imageTag: dev

embeddingService:
  image:
    repository: ols4-embed
    pullPolicy: IfNotPresent
    tag: ""
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
