apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: standard-nfs-production
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi

