name: Docker Image CI

on:
  push:
    branches: [ "docker-automation" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build dataload docker image
      run: |
        cd dataload
        docker build -t ols4-dataload .

