name: Build & Test

on:
  push:
    branches: [ "dev", "stable", "nextflow" ]
  pull_request:
    branches: [ "dev", "nextflow" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  testDataload:
    name: Data Load Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -ntp -B clean package -Dmaven.compiler.release=${{ matrix.java }}
      - name: Run dataload tests
        run: ./test_dataload.sh

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    if: ${{ github.repository_owner == 'EBISPOT' }}

    strategy:
      matrix:
        component: [dataload, backend, frontend, apitester4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ebispot/ols4-${{ matrix.component }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Build and push ols4 ${{ matrix.component }} Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component == 'frontend' && './frontend' || (matrix.component == 'apitester4' && './apitester4' || '.') }}
          file: ${{ matrix.component == 'frontend' && './frontend/Dockerfile' || format('./{0}/Dockerfile', matrix.component) }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ebispot/ols4-${{ matrix.component }}:${{ github.sha }}
            ghcr.io/ebispot/ols4-${{ matrix.component }}:${{ github.head_ref || github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  testApi:
    name: API Tests
    runs-on: ubuntu-latest
    needs: [testDataload, build-and-push-image]
    if: ${{ github.repository_owner == 'EBISPOT' }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Docker images
        run: |
          docker pull ghcr.io/ebispot/ols4-backend:${{ github.sha }}
          docker pull ghcr.io/ebispot/ols4-frontend:${{ github.sha }}
          docker pull ghcr.io/ebispot/ols4-apitester4:${{ github.sha }}
          echo "OLS4_BACKEND_IMAGE=ghcr.io/ebispot/ols4-backend:${{ github.sha }}" >> $GITHUB_ENV
          echo "OLS4_FRONTEND_IMAGE=ghcr.io/ebispot/ols4-frontend:${{ github.sha }}" >> $GITHUB_ENV
          echo "OLS4_APITESTER_IMAGE=ghcr.io/ebispot/ols4-apitester4:${{ github.sha }}" >> $GITHUB_ENV
      - name: Run API tests
        run: ./test_api.sh
