name: Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  testDataload:
    name: Data Load
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Run dataload tests
        run: ./test_dataload.sh
  testApi:
    name: API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run API tests
        run: ./test_api.sh
