name: Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  testDataload:
    name: Data Load
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        # -ntp gets rid of the "Downloading..." spam
        run: mvn -ntp -B clean package -Dmaven.compiler.release=${{ matrix.java }}
      - name: Run dataload tests
        run: ./test_dataload.sh
#  testApi:
#    name: API
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run API tests
#        run: ./test_api.sh
